### ISSUE TITLE
UICatalog: Character Map scenario scrolling is unusably slow

### ISSUE THREAD

**Issue by tig** [gui-cs/Terminal.Gui#1743]
Using the scroll bars in Character Map is unusable because rendering is taking too long. 

Need to look into making it more usable.

**Comment by tig** [comment]
@BDisp's #1764 helps with this. But whatever I'm doing in my rendering is still too slow I think. So I'm leaving this open.

**Comment by BDisp** [comment]
Well this behavior depends on the console used. if with the `vs debugger console`, works fine. On the `Windows Terminal` with `WindowsDriver` and `CursesDriver` it's freezing so much and with `NetDriver` work well on `Windows` and `Linux`. I think `Windows Terminal` is not rendering well the mouse pressed with movement events with `WindowsDriver` and `CursesDriver`, maybe it's expecting to receive `escape sequences` instead of `Win32` and `ncurses` instructions.

**Comment by BDisp** [comment]
Forget about i said above, it's really a big bug that I'll fix. I already found it.

**Comment by tig** [comment]
#1743 helps, but i don't think the root of this Issues is ScrollView or mouse related. 

I just need to optimize how Character Map does it's processing.

**Comment by BDisp** [comment]
See this please https://github.com/migueldeicaza/gui.cs/pull/1765#issuecomment-1145401004

**Comment by tig** [comment]
> See this please [#1765 (comment)](https://github.com/migueldeicaza/gui.cs/pull/1765#issuecomment-1145401004)

Yes, I saw that. But my concerns have nothing to do with the mouse (now that you've fixed those issues). The performance of the scrolling is not as good as I'd like when I use the keyboard to scroll.

**Comment by BDisp** [comment]
I understand what you mean. Perhaps it's a good idea to load only the next or previous data, sending a size like all data was load. This way the scrollbar view will only load the data to be drawn accelerating the scrolling.
