### ISSUE TITLE
new View has null X/Y/Width/Height

### ISSUE THREAD

**Issue by tznind** [gui-cs/Terminal.Gui#1927]
**Describe the bug**
Not sure if this is a bug but it is a change in behaviour so thought I would report it.

Previously a new View would have a X/Y of 0 and Width/Height of 0.  Now they are null.

```csharp
var v = new View();
Assert.IsNull(v.Width, "As of v1.7.0 a new View started getting null for its Width");
```

I think this will only affect a very small number of users who are querying these properties before it has been added to a container.  For example the fix I applied to TerminalGuiDesigner is to treat null as Absolute(0) for Pos and Dim:

https://github.com/gui-cs/TerminalGuiDesigner/pull/58/commits/506b556ccde04219db8a4710ef318f2df1b427cb

**Comment by BDisp** [comment]
@tznind that change was essential to check if a `Pos/Dim` was setting by the user or not and the only way to check this is they are null. If a `Rect` is provide on initialization the view `LayoutStyle` will be `Absolute` and thus the `Pos/Dim` aren't necessary because it will not run the `SetRelativeLayout`. For `Compute` layout null `Pos/Dim` will be fit in the superview container. Without this changes I couldn't deal well with the auto-size issue. Do you remember when you said before that a view with auto-size enable respect the minimum width/height on shrinking and expand on growing? Only with this change I could do that. The changes didn't affect none of the samples nor unit tests except the null checks.

**Comment by tznind** [comment]
Ok cool, I thought it was probably intentional but worth documenting anyway.  Thanks.  I think it is ok and will close.
