### ISSUE TITLE
MenuBar: Support `Title` so that a Window (with wasteful border) is not needed to show app title

### ISSUE THREAD

**Issue by tig** [gui-cs/Terminal.Gui#2108]
Something like this:

<img width="234" alt="image" src="https://user-images.githubusercontent.com/585482/196820775-c9216063-1bd5-42a4-a2ff-b512c29d98d1.png">

But, make it obvious that "Notepad" is not part of the menu.

Perhaps right align the title? Might be weird.

Perhaps, a different color?

Perhaps, a different background color?

Perhaps, just a dash after? (`Notepad -`)?

**Comment by tznind** [comment]
What about something like this:

![menubartitle](https://user-images.githubusercontent.com/31306100/196873708-16850338-ed23-4b25-a425-eddb6a7deaf9.jpg)

The layout would need to be:

Align center (as above) unless:

- If menus fill whole horizontal space then hide title
![hidetitle](https://user-images.githubusercontent.com/31306100/196874929-4958c020-72c9-4cc4-9040-145b8bcca58f.jpg)

- If menus go past half way then align title right instead of center
![alignright](https://user-images.githubusercontent.com/31306100/196874982-360d2c24-5c24-4232-9e33-67262f8eabbe.jpg)

**Comment by tznind** [comment]
Adding hyphens looks pretty cool too, although probably should be optional or just a convention we use in UICatalog (i.e. `Title="-mytitle-"`).

![hyphentitle](https://user-images.githubusercontent.com/31306100/196875779-4e43c3cf-5c27-4194-8faf-438cb687820c.jpg)

**Comment by tig** [comment]
Great ideas @tznind -

FWIW, while I should be working on higher-priority stuff, I sucked myself into the Menu and MenuTests code yesterday. I am doing a major refactoring of the tests because they are super fragile. This will (hopefully) enable updating a bunch of this stuff easily.

**Comment by tig** [comment]
Closing. This will be addressed in #2975
