### ISSUE TITLE
UI Catalog: Changing Keybindings has no effect

### ISSUE THREAD

**Issue by tig** [gui-cs/Terminal.Gui#2131]
I was curious so I tried to change `QuitTopLevel` to "CTRL-T"

<img width="363" alt="image" src="https://user-images.githubusercontent.com/585482/197226727-3994a8ef-e0be-4a0e-bbb7-cb7a25f83798.png">

I expected the app to quit if I hit CTRL-T. Nothing happens.

Am I missing something or is this broken?

**Comment by tznind** [comment]
Can confirm that I am seeing an issue with this.

After changing Quit to Ctrl+T and opening a Scenario I find that Ctrl+Q no longer works but Ctrl+T also does not work (cannot exit scenario!).

But I can change for example `PageDown` Command from the `PageDown` key to `Shift+PageDown`.  That works in the list view and also other Scenarios that are launched.

So I think that the `ViewTracker` and `Keybinding` system itself is working but this issue is either limited to `Quit` or to some subset of commands.

**Comment by tig** [comment]
Closing. dupe of

- #3120
