### ISSUE TITLE
ListView: OnSelectedChanged is called when it didn't actually change (OnEnter)

### ISSUE THREAD

**Issue by tig** [gui-cs/Terminal.Gui#2140]
<img width="715" alt="image" src="https://user-images.githubusercontent.com/585482/198855974-530b58ba-5b13-407b-aa64-8c6291ff8ae2.png">

Because of this, there's no way for an override to know if the selection REALLY changed. 

In UI Catalog, this means that whenever the focus returns to the Category ListView, the Secenario ListView gets regenerated, causing IT to lose what Scenario was previously selected:

![00ibvTI 1](https://user-images.githubusercontent.com/585482/198856037-40e5281f-858a-447b-bf15-be3e3c18a2d2.gif)

I believe the call to `OnSelectedChanged` in `OnEnter` should be removed.

@BDisp - what do you think?

**Comment by BDisp** [comment]
Actually the item is only selected if the Enter key or double click was used. That why the item is never selected. The reason why the `OnSelectedChanged` is called in `OnEnter` is because when a `ListView` is instantiated the selected item is always 0, even is empty, and no event is fired to subscribers to update some state. I think the best solution is instantiate with the selected item equal to -1, unless it set on the property. In the `OnEnter` if the selected item is equal to -1 then selected the first item if not empty.

**Comment by tig** [comment]
I do not understand you OR you are confused about how a list box is supposed to work.

Moving up/down in a list box with keyboard should change the current selection.

**Comment by BDisp** [comment]
> I do not understand you OR you are confused about how a list box is supposed to work.
> 
> Moving up/down in a list box with keyboard should change the current selection.

You are right, sorry. I was confused with the `OnOpenSelected`. But about updating the state throw an event on initializing is true and that why it is in the `OnEnter`. How about saving the current selected item in a variable to restore after regenerated?

**Comment by tig** [comment]
I don't understand, sorry.

**Comment by BDisp** [comment]
> I don't understand, sorry.

Suppose the last selected item was 3 and is saved to a variable. After the scenario listview is regenerated set the selected item with that variable.

**Comment by tznind** [comment]
As I understand it, @tig  is saying that `OnSelectedChanged`  event should not be fired in the `OnEnter` method of ListView:

https://github.com/gui-cs/Terminal.Gui/blob/af7901066a326533458f5b5fd56049c98cfb2d39/Terminal.Gui/Views/ListView.cs#L706-L709

@BDisp are you describing a scenario where having this call in OnEnter is important?  

To me it makes sense to remove it as system should be reporting a single action (i.e. Enter) and out of the box no selection changes when you Enter the control so firing `OnSelectedChanged` makes no difference.  I agree obviously that if the user hooks Enter and provides a callback that updates the selection that itself would trigger the changed event.

**Comment by tig** [comment]
> But I do see the conditional of `lastSelectedItem == -1`... which I don't fully understand (how it relates to Enter / whether or not to fire OnSelectedChanged from the perspective of an API user)

I don't understand the `lastSelectedItem` code either. I looked at hard and just got more confused.

Let's step back to fundamentals and ensure we're on the same page:

- A `ListView` with `AllowsMultipleSelection == false` (the default behavior) can have a  single item in `Source` selected. `ListView.SelectedItem` sets/gets this index. This item is drawn in such a way that it is apparent to the user that it is selected (`HotNormal` or `Focus` depending on whether the `ListView` has focus or not).
- It is possible (programmatically; there is no user input way) to make a single-selection `ListView` have NO item selected. `SelectedItem` will be `-1` in this case. By default, when a `ListView` is created, `Source` set, `SelectedItem` is set to `-1`. **
- The `OnSelectedChanged` override is called whenever `SelectedItem` changes. It should ONLY be called if the `SelectedItem` actually changes. That is how it worked when @BDisp added it in commit ID d54f620b (pr #485).

In PR #1081, @BDisp added `EnsuresVisibility...` and added the `OnSelectedChanged()` call to `OnEnter`. This broke the previous behavior, which I just discovered. 
 
** I believe this (setting `SelectedItem` to `-1` on setting `Source` is the wrong behavior. I'd prefer it if the first item was selected by default, but it's not a big issue. 

@BDisp `lastSelectedItem` seems mis-named or something. Can you please explain what your intent was in adding it?

**Comment by BDisp** [comment]
> I don't understand the `lastSelectedItem` code either. I looked at it hard and just got more confused.

Well, that I know the `SelectedItem` never was equal to -1 as initial value but equal to 0. The backed field is the `selected`. I never liked this initial setting but that was how it was. When the `ListView` get the focus another view that subscribe the `SelectedChanged`, never get fired because the selected item was 0 and the view doesn't get notified to fill his value. That why I created another variable `lastSelectedItem` with the initial value equal to -1. If the selected item is 0 and the lastSelectedItem == -1, the the subscriber is notified by the event to fill the values. Is wrong or not depend on how the ListView creator wants the selected item is greater than -1 if it has items. I started get this issue when I created the `DynamicMenuBar` and the `DynamicStatusBar` scenarios. But I agree the subscriber can subscribe the `Enter` event to get the initial value.

**Comment by tig** [comment]
@BDisp do you know what will break if we fix this bug and change `OnEnter` to not call `OnSelectedChanged`?

**Comment by BDisp** [comment]
> @BDisp do you know what will break if we fix this bug and change `OnEnter` to not call `OnSelectedChanged`?

I really don't know. Maybe the `ComboBox` too. But if I was you I'll go ahead with also remove the `lastSelectedItem` and using the `selected` to be -1 if there are no items and in the `SelectedItem` only call the `OnSelectedChanged` if it was changed. But also is needed very careful because the `select` field is set along the code without call the `OnSelectedChanged` and must do.
If you fell fine remove it or doing some unit test with a view getting the selected item from `ListView` when that view gets the focus.
