### ISSUE TITLE
Statusbar misplaced when window maximised (and occasionally on resize)

### ISSUE THREAD

**Issue by fluffynuts** [gui-cs/Terminal.Gui#2226]
**Describe the bug**
Demo project: https://github.com/fluffynuts/tsm (apologies, it's a bit of a hacked-together thing right now, but it does demonstrate the issue on windows).

When cmd or pwsh or Windows Terminal are maximised and I start up services.exe, the status bar is stuck to the top of the root window (may also be invisible up there) instead of the bottom. Resizing the window makes it (mostly) go to the bottom again, but sometimes it disappears.

**To Reproduce**
1. Requires a windows machine
2. launch cmd.exe or windows terminal or pwsh.exe, maximise, cd to project dir
3. `npm start` in https://github.com/fluffynuts/tsm
4. status bar will either be missing (obscured) or on the top of the console
5. resize slowly - it will jump to the bottom, and back up again sometimes, though it mostly stays on the bottom. Maximise again, and the status bar will disappear.
6. starting the app in a non-maximised console has the statusbar in the correct place (bottom)

**Expected behavior**
StatusBar, having been pinned to the bottom of the root window, should stay there.

**Screenshots**
maximised:
![image](https://user-images.githubusercontent.com/4669340/202219527-a78334ed-0db0-49a1-adc3-a4d160bb59e3.png)
resized:
![image](https://user-images.githubusercontent.com/4669340/202219611-1224fb60-39f2-4118-bef6-29d8d7afa5c9.png)
non-maximised start:
![image](https://user-images.githubusercontent.com/4669340/202219813-f711b797-97f9-4d8d-8eef-d2e54ee57296.png)

**Desktop (please complete the following information):**
 - OS: Windows 11, dotnet 6.0 or 7.0 (same result)

(edited: I had to change the name of the project because `services.exe` doesn't work in the path - windows keeps trying to launch `services.msc` and failing - so now it's `tsm` - Terminal Service Manager)

**Comment by tznind** [comment]
Thanks for raising this.

Looks like you are positioning the StatusBar with `Y = Pos.Bottom(this),`.  There may be underlying issues that need tackled in the API but to fix your specific case I think you could do the following:

- Change the MainView class to have ` Height = Dim.Fill(1);` (fill screen but leave 1 space below)
- Add the `StatusBar` to the `Application.Top` instead of the window

Or if you want to keep it in the window you could try:

- Changing StatusBar Y to `Pos.AnchorEnd(1)` instead of `Bottom`.

**Comment by tig** [comment]
FWIW, not that I'd ever encourage anyone to not build TUI app but...

```pwsh
get-service | Where-Object {$_.Status -EQ “Stopped”} | Out-ConsoleGridView | { start-service -name $_.name }
```

;-)

**Comment by fluffynuts** [comment]
yeah, there's plenty of ways to handle service start / stop - one of the benefits of mine is that operations are asynchronous - which is helpful for a situation we have where we run 2 services for each country we service with our application - about 7 in total, so 14 services - and those services take a few seconds to start and stop (up to 10, typically, due to long-running logic), so being able to filter on services and restart all of them in one go (or stop them all) is kinda handy - services.msc blocks during this operation, and start-service does the same - with my little tui, I can signal to start a service and move on, or filter a group and start/stop/restart them all at one time, no waiting. This was the main reason for hacking this together :D

**Comment by fluffynuts** [comment]
Ok, for anyone else who stumbles across this, the main problem (I think) was that I was calling `Application.Run(new MainWindow())`. If I follow the advice of @tznind and put the status bar on `Application.Top` - but _also, very importantly, add my own `MainWindow` to the existing `Application.Top` and then `Application.Run(Application.Top)`, then the statusbar behaves very well.

This services tool is now ready to show my team - I know at least one person who is going to like it, because he was just as annoyed as I was to have to wait for services.msc to complete state changes on each individual service.

**Comment by tznind** [comment]
Great, glad that you got it sorted! Let us know how your team gets on.  Its always nice to hear from library users.

If you are creating more small tools like this in the future you might want to try the Designer which can speedup the boilerplate stuff: https://github.com/gui-cs/TerminalGuiDesigner#terminal-gui-designer

**Comment by BDisp** [comment]
@fluffynuts thanks for reporting this. A `MenuBar` inside a `Window` is working well by always standing on the top, but a `StatusBar` inside a `Window` really fail by not always standing on the bottom. I'll try to fix this, but I need to give some advice on this. Having them inside a `Window` the user is responsible to deal with the position of the other views only. So the top position of the other views must be greater or equal to one and the bottom position must be lower or equal to minus one. Otherwise the views will be under the `MenuBar` on top and under the `StatusBar` on bottom.
