### ISSUE TITLE
HeightAsBuffer is confusingly named

### ISSUE THREAD

**Issue by tig** [gui-cs/Terminal.Gui#2303]
See the comments in PR #2264 

This will be fixed by #2264 (current proposal is `EnableConsoleScrolling`.

**Comment by BDisp** [comment]
@tig I propose the bellow approach covering more options:

```cs
public enum VerticalScrollBehavior {
	// No scroll at all.
	None,
	// Only allow scrolling into the app.
	AppScrolling,
	// Allow scrolling on all scrollback buffer (original buffer more app buffer)
	// This allows an app write to the console preserving with all scrollback buffer.
	ScrollBackBuffer
}
```

**Comment by BDisp** [comment]
Or also since thie suggested `enum` has 3 options can be used a nullable bool:
* **Null** - Means that the buffer is handled by the terminal (for scrollback buffer).
* **False** - Means that no scrolling is used.
* **True** - Means that the app will show the scroll as necessary and its buffer is managed by the app.
