### ISSUE TITLE
Weird string value written to the standard output

### ISSUE THREAD

**Issue by chr1st0scli** [gui-cs/Terminal.Gui#2325]
**Unwanted std out side effect on window resize**
The library (or one of its dependencies?) seems to write the string value "\u001b[3J" to the standard output under certain circumstances. As a result, if one has decided to redirect the standard output to some UI component, such as a TextView, they see this weird string value the first time the application starts and whenever the window size changes.

**To Reproduce**
1. Create a console GUI app with a multiline text view (the component and its multiline attribute should be irrelevant).
2. Redirect the standard output like so:  `Console.SetOut(outputWriter);` where outputWriter is a TextWriter that writes to the text view.
3. Start the application and observe the the weird string value written to the text view.
4. Resize the window or enter and exit full screen and observe the same value written multiple times.

**Expected behavior**
This string value should not be written to the standard output.

**Screenshots**
![Screenshot 2023-02-06 204536](https://user-images.githubusercontent.com/5046010/217058404-7bf32713-2f98-43a6-954b-8db3f43a6169.png)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by BDisp** [comment]
Try with this PR #2264 and check this isn't happening.

**Comment by tznind** [comment]
If you move cursor around and click do you see other escape codes comming through?

**Comment by BDisp** [comment]
That not the case @tznind. The `WindowsDriver` (@chr1st0scli please confirm if you are running this driver) don't recognize escape sequence, so it's echoed to the console output and this code if for clear the buffer.

**Comment by chr1st0scli** [comment]
> Try with this PR #2264 and check this isn't happening.

Hi @BDisp I just tried the proposed PR. Indeed the weird string value has stopped appearing but unfortunately it has been replaced by another one, namely "\u001b[0J"

**Comment by BDisp** [comment]
I already expected that. Was changed from "\u001b[3J" to "\u001b[0J". This code is in the `ResizeScreen` method of the `WindowsDriver.cs`. Removing it solves the issue. That PR is still under development, I think. `WindowsDriver` can not have escape sequences because it isn't configured to use virtual terminal, so it's supposed to output that characters if the console output is redirected, on theses terminals (cmd, vsdebugger, conhost, pwsh). Strangely the escape sequences are executed on the `Windows Terminal` but, unfortunately still have some incompatibilities with legacy terminal, like not allowing resize the console buffer size but only the window size.

**Comment by chr1st0scli** [comment]
> That not the case @tznind. The `WindowsDriver` (@chr1st0scli please confirm if you are running this driver) don't recognize escape sequence, so it's echoed to the console output and this code if for clear the buffer.
> 
> **Edit:** Your solution is great @tznind.

@BDisp I am not sure how I can determine with certainty the thing you are asking about WindowsDriver. I am not sure what we are talking about. My OS is windows though. If you are referring to the class, no I am not directly using it as it is internal in the library.

**Comment by BDisp** [comment]
Ok no problem. For your information there are 3 official drivers and another for tests (`FakeDriver`).

**If you are running on a Windows OS:**
- If you running with the `Application.UseSystemConsole` as `false` (default) then you are using the `WindowsDriver`.
- If you running with the `Application.UseSystemConsole` as `true` then you are using the `NetDriver`.

**If you are running on a Linux or macOS:**
- If you running with the `Application.UseSystemConsole` as `false` (default) then you are using the `CursesDriver`.
- If you running with the `Application.UseSystemConsole` as `true` then you are using the `NetDriver`.

So the `NetDriver` is a cross platform driver but more slower.

**Comment by chr1st0scli** [comment]
Hi @BDisp 

- I have noticed that "\u001b[3J" is no longer written when using the `WindowsDriver`. (Noticed since 1.14.0 I think)
- I still need to ignore "\u001b[0 q" or "\u001b[1 q" when using the `CursesDriver`.

Should I close this bug or is the second information above of some value?

**Comment by BDisp** [comment]
What does the escapes sequences in the second information?

**Comment by chr1st0scli** [comment]
The "\u001b[1 q" is being printed by the CursesDriver (I have tried it with a docker container using alpine).

![image](https://github.com/gui-cs/Terminal.Gui/assets/5046010/888c8523-40c9-47d2-84ef-a5a73d76a5e2)

**Comment by chr1st0scli** [comment]
If you are interested to reproduce, I have a temporary branch here https://github.com/chr1st0scli/RainLispConsole/tree/terminalgui-bump

But you have to comment out lines 26 & 27 in OutputTextViewWriter.cs and try out in Linux.

**Comment by BDisp** [comment]
I already know what is going on here. The cause of the output is `CursesDriver` escape sequence `Console.Out.Write ("\x1b[{0} q", ((int)visibility >> 24) & 0xFF);` which handles the cursor visibility. When you exit the application you'll see that mouse escape sequences are echoed to the console. The main cause of the issue is the fact you are redirecting the output to a custom `TextWriter`. You must prevent using the redirection before the app is loaded and after is unloaded. The Ansi escape sequences must always run on the original console output.
Maybe you can use the toplevel `Loaded` and `UnLoaded` events to restore the output redirection.

**Comment by chr1st0scli** [comment]
Thanks!
