### ISSUE TITLE
LineCanvas `GenerateImage` and `Draw` assume bounds' location is always `0, 0`

### ISSUE THREAD

**Issue by tig** [gui-cs/Terminal.Gui#2343]
This test illustrates:

```cs
		[Fact, AutoInitShutdown]
		public void TestLineCanvas_PositiveLocation ()
		{
			var x = 1;
			var y = 1;
			var v = GetCanvas (out var canvas, x, y);

			// outer box
			canvas.AddLine (new Point (x, y), 9, Orientation.Horizontal, BorderStyle.Single);
			canvas.AddLine (new Point (x + 9, y + 0), 4, Orientation.Vertical, BorderStyle.Single);
			canvas.AddLine (new Point (x + 9, y + 4), -9, Orientation.Horizontal, BorderStyle.Single);
			canvas.AddLine (new Point (x + 0, y + 4), -4, Orientation.Vertical, BorderStyle.Single);


			canvas.AddLine (new Point (x + 5, y + 0), 4, Orientation.Vertical, BorderStyle.Single);
			canvas.AddLine (new Point (x + 0, y + 2), 9, Orientation.Horizontal, BorderStyle.Single);

			v.Redraw (v.Bounds);

			string looksLike =
@"    

 ┌────┬───┐
 │    │   │
 ├────┼───┤
 │    │   │
 └────┴───┘";
			TestHelpers.AssertDriverContentsAre (looksLike, output);
		}

		private View GetCanvas (out LineCanvas canvas, int x = 0, int y = 0)
		{
			var v = new View {
				Width = 10,
				Height = 5,
				Bounds = new Rect (x, y, 10, 5)
			};

			var canvasCopy = canvas =  new LineCanvas ();
			v.DrawContentComplete += (r)=> canvasCopy.Draw (v, v.Bounds);

			return v;
		}
```

```

Message: 
Assert.Equal() Failure
                   ↓ (pos 9)
Expected: ┌────┬───┐\n │    │   │\n ├────┼───┤\n │    │   │\n └─···
Actual:   ┌────┬───\n │    │\n ├────┼───\n │    │
                   ↑ (pos 9)
```

I'm confused about the right way to fix this (I need more caffeine or something):

https://github.com/gui-cs/Terminal.Gui/blob/2ead01a3c8fea7dc449483230c6fcab2b2bf7f90/Terminal.Gui/Core/Graphs/LineCanvas.cs#L49-L101

Should the result of `GenerateImage` always have the lines rooted at `0, 0` or should it be offset by `bounds.Location`?

I expected this change to line 68 would fix it:

```cs
						.Select (l => l.Intersects (inArea.X + x, inArea.Y + y))
```

But it didn't. I suspect there's a related bug in the `GetRuneForIntersects` path, but I'm not smart enough see what it is.

I discovered the need for this when attempting to refactor `View` (via `Border.DrawContent` to use `LineCanvas` instead of `Driver.DrawFrame`.

**Comment by tznind** [comment]
`LineCanvas` doesn't make any assumptions about the coordinate space while lines are built or resolved. 

This is deliberate so that it is flexible for reuse (e.g. in `GraphView` or other places it might be handy).  You can even have lines that fit into negatives (e.g. a line that starts at -5,0).  You can freely use values like `Int.MaxValue` if you want without issue.

To turn the lines and coordinate space into a renderable set of runes (i.e. a bitmap) you use `GenerateImage` with any rectangle clipping you want.  This will give you a 2d array with that section of the 'image'.  You are then free to draw that bitmap with whatever offset you want (e.g. to translate to screen cordinates, tile over and over in a view etc).

The only time a `View` specific coordinate space is imposed is in `public void Draw (View view, Rect bounds)`.  In fact the only reference to `View` at all is in the `Draw` method.

**Comment by tznind** [comment]
Oops forget all that, think I get what you mean
