### ISSUE TITLE
`Pos.Combine` is incorrect for scenarios involving `PosAbsolute`

### ISSUE THREAD

**Issue by tig** [gui-cs/Terminal.Gui#2358]
Change the `ComputedScenario` to add an additional button like this:

```cs
                       Win.Add (rightButton);
....
			centerButton = new Button ("0 + Center") {
				X = 0 + Pos.Center (),
				Y = Pos.AnchorEnd (2)
			};
			Win.Add (centerButton);
```

Expected:

The new button is centered in the view.

Actual:

<img width="572" alt="image" src="https://user-images.githubusercontent.com/585482/220037256-8763342b-f40a-4336-8197-77211d5643e2.png">

The bug is in `View.SetRelativeLayout`. It needs to check for `PosCombine` and iterate through `PosCombine.left` and `PosCombine.right` to adjust the relative location properly. 

I'm not actually sure it is possible to deal with all combinations. This may not be worth fixing.

Related: 

* What would you expect `Pos.Center() + Pos.Center()` to do?
*  What would you expect `Pos.Percent() + Pos.Center()` to do?
* How about `Pos.Percent(20) + Pos.Percent(20)`? (this one's obvious: just like `Pos.Percent(40)`).
etc...

**Comment by BDisp** [comment]
> The bug is in `View.SetRelativeLayout`. It needs to check for `PosCombine` and iterate through `PosCombine.left` and `PosCombine.right` to adjust the relative location properly.
> 
Right, the `View.SetRelativeLayout` have to send the `PosCombine` to the `PosCombine` class which will calculate the appropriate layout value.

> I'm not actually sure it is possible to deal with all combinations. This may not be worth fixing.
> 
Depends if it has any logic or not.

> Related:
> 
>     * What would you expect `Pos.Center() + Pos.Center()` to do?
> 
My opinion is that it doesn't sense because is the same as using `Pos.AnchorEnd` (100/2=50+100/2=50=100) and also `Pos.Center() - Pos.Center()` is the same as using `PosAbsolute` equal to zero (100/2=50-100/2=50=0).

>     * What would you expect `Pos.Percent() + Pos.Center()` to do?
> 
Without percent value it doesn't make sense (is the same as only using  `Pos.Center()`), but with percent value it does make sense because it will calculate the percentage area and the will add more center value (eg. 100*20%=20+100/2=50=70).

>     * How about `Pos.Percent(20) + Pos.Percent(20)`? (this one's obvious: just like `Pos.Percent(40)`).
Right (100*20%=20+100*20%=20=40 so it's the same as 100*40%=40)

>       etc...
Ask for more :-)

**Comment by tig** [comment]
Thanks. BTW, I have a refactor of all this in progress that fixes this an simplifies the code significantly. I believe I can make it work in a backwards compatible way.

**Comment by BDisp** [comment]
> Thanks. BTW, I have a refactor of all this in progress that fixes this an simplifies the code significantly. I believe I can make it work in a backwards compatible way.

If is a backwards compatible merge it in the develop (v1) first and then merge it in the v2 while V2 is not released.

**Comment by tig** [comment]
Thanks. BTW, I have a refactor of all this in progress that fixes this an simplifies the code significantly. I believe I can make it work in a backwards compatible way.

**Comment by tig** [comment]
Changed title since this is not such a big deal now that it's targeting v2.

**Comment by BDisp** [comment]
Can this be closed as completed?
