### ISSUE TITLE
Launching a Dialog from a Dialog causes errors in v2_develop

### ISSUE THREAD

**Issue by tznind** [gui-cs/Terminal.Gui#2430]
**Describe the bug**
First encountered this bug in https://github.com/gui-cs/Terminal.Gui/pull/2259#issuecomment-1475190039

Here is a minimum repo:

```csharp
Application.Init ();
var btn1 = new Button ("press me 1");
var btn2 = new Button ("Show Sub");
var btn3 = new Button ("Close");
btn3.Clicked += () => Application.RequestStop ();
btn2.Clicked += () => { MessageBox.Query ("hey", "ya", "ok"); };
var dlg = new Dialog ("Hey", btn2,btn3);
btn1.Clicked += ()=>Application.Run (dlg);
var w = new Window ();
w.Add (btn1);
Application.Run (w);

Application.Shutdown ();
```

**To Reproduce**
1. Click button
2. Click 'show sub'
3. Close sub

**Expected behavior**
Sub should close leaving the Dialog still showing but instead the sub border still shows and system becomes unstable.

**Screenshots**
![image](https://user-images.githubusercontent.com/31306100/226183279-f823c49b-11bd-4548-a3d4-daa46e1f51a9.png)

**Comment by BDisp** [comment]
I already reverted all my PR but the still exist. I'll investigate it.

**Comment by BDisp** [comment]
@tznind this should be like this because the dialog is destroyed when exit and if you want to run again you must recreate it.
```cs
	Application.Init ();
	var btn1 = new Button ("press me 1");
	btn1.Clicked += () => {
		var btn2 = new Button ("Show Sub");
		var btn3 = new Button ("Close");
		btn3.Clicked += () => Application.RequestStop ();
		btn2.Clicked += () => { MessageBox.Query ("hey", "ya", "ok"); };
		var dlg = new Dialog ("Hey", btn2, btn3);

		Application.Run (dlg);
	};
	var w = new Window ();
	w.Add (btn1);
	Application.Run (w);

	Application.Shutdown ();

```

But the issue remain, I think that is because the `Border` is now like a static property due the configuration and the previous dialog has the property of the `MessageBox` border property after closed. I already realized that something is wrong because of the static configurations which I would like @tig can say something about.

**Comment by BDisp** [comment]
What is going on with this issue is the fact that the sub-dialog is overwriting the first Dialog.
