### ISSUE TITLE
GraphView needs to be refactored to use new View `Frames`

### ISSUE THREAD

**Issue by tig** [gui-cs/Terminal.Gui#2463]
This stuff is now redundant:

https://github.com/gui-cs/Terminal.Gui/blob/33c9a5fad44256ab1ade0d9ac478dab6af89b9b6/Terminal.Gui/Views/GraphView.cs#L37

I will be disabling the GraphView unit tests in #2361 for now. The `Graph View` scenario works fine, but the tests are failing and I don't want to spend any more time debugging. We can fix the unit tests when this issue is addressed.

**Comment by tznind** [comment]
I can take a look after I've finished with the new file dialog (and its component PRs: #2455 and #2466  )

For context:

`GraphView`  provides a scrollable/zoomable `float` based coordinate space (referred to as 'graph space').  `ISeries` and `IAnnotation` can be added to this space.  These are rendered but cannot have focus  / clickable etc.  At ReDraw time the `float` coordinate space (at the current scroll/zoom) is projected into 'screen space' which is the client area of the `GraphView`) i.e. rows/cols (`int`). 

The `Margin` properties determine where the graph space starts within the `View`.  The axis and axis title are typically drawn into this area.  Switching to use a seperate `View` for the axis and putting them into the new borders system should be pretty cool and open up some interesting possibilities for interactivity.

**Comment by tig** [comment]
> I can take a look after I've finished with the new file dialog (and its component PRs: #2455 and #2466 )

No real rush; as noted it still works fine, there's just some issues with the unit tests.

> The `Margin` properties determine where the graph space starts within the `View`. The axis and axis title are typically drawn into this area. Switching to use a seperate `View` for the axis and putting them into the new borders system should be pretty cool and open up some interesting possibilities for interactivity.

Right. But your definition of `Margin` is backwards from how the web works (and how v2 will work).

`Margin` is the area between subviews.
`BorderFrame` (to be called `Adornments`) is where the border (and things like menus/scrollbars) get drawn.
`Padding` is the the spacing inside `Margin` and `Adornments` that defines the `content area` (aka `Bounds`).

With v2, `GraphView` will not need it's own concept of `Margin`; the same thing will be achieved by just leveraging `Padding`.

**Comment by tznind** [comment]
> I will be disabling the GraphView unit tests in #2361 for now.

It looks like the tests are enabled again? They seem to all be passing on `v2_develop`.

I agree 'Margin' needs looked at and at the very least renamed.

But I want to start with a clear explanation of what the feature does at the moment.

### Current Role

MarginLeft and MarginBottom (there is no right/left margin) result in the following behaviours:

- Create a 'no go' zone for axis lines (axis lines stop at margins)
- Move the origin of the graph by an absolute number of 'screen units'

It is worth noting that Series can still render into these margins (plot points in margins is allowed and rendered).  As can axis labels. See for example where `-2.40` is centered on axis beginning at the edge of the margin.  Because label is centered it spills into margin.

The typical use case for margins is to push the graph up/right to make space for 'stuff' that is very much part of the graph but would otherwise fall off the screen.

The other process for moving the origin is 'Scroll Offset'.  Scroll Offset changes where the origin of the graph is.  It is how the user can scroll around inside the graph and how the sine wave is centered.

Scroll Offset:

- Is measured in 'Graph Space' (i.e. float)
- Moves the series and axis but not anything positioned in 'screen space' (titles, annotations, legends etc).

![image](https://user-images.githubusercontent.com/31306100/230724772-2100e66d-3c46-42ce-9e1b-37afab97a1a3.png)

![image](https://user-images.githubusercontent.com/31306100/230725473-7c53c4bd-c988-42f2-b34d-52e14b15b32c.png)

**Comment by tig** [comment]
> > I will be disabling the GraphView unit tests in #2361 for now.
> 
> It looks like the tests are enabled again? They seem to all be passing on `v2_develop`.

Yep. Turns out I didn't break things as badly as I thought ;-)
