### ISSUE TITLE
MenuBar positions wrong in some situations

### ISSUE THREAD

**Issue by tznind** [gui-cs/Terminal.Gui#2558]
**Describe the bug**

Running FileDialog with the following code results in a MenuBar that is mis positioned and has trailing corruption on right.  I think it is to do with running using `Application.Run` directly without having a `Top` yet?  The issue does not manifest in the `FileDialogExamples` scenario.

```csharp
Application.Init ();
var dlg = new SaveDialog ("Save my file",
new List<IAllowedType> { new AllowedType("Comma Separated File",".csv") });

Application.Run (dlg);

if (!dlg.Canceled) {
    MessageBox.Query ("File Chosen", $"You chose {dlg.Path}", "Ok");
}

Application.Shutdown ();
```

![image](https://user-images.githubusercontent.com/31306100/232335640-28a2275b-de82-477d-aaae-019503a3578c.png)
_Opening the MenuBar when running with the above code_

Notice how the issue does not manifest in Scenario:

![image](https://user-images.githubusercontent.com/31306100/232335769-9fa880e8-570b-4978-a02f-d0af9ee68b8c.png)
_Opening the MenuBar when running in Scenario_

**Comment by BDisp** [comment]
@tig I thing you should avoiding use capital letters variables for parameters, like as this:

`public static RunState Begin (Toplevel Toplevel)`

In this case if you have a property `Toplevel Toplevel {get;}` and want to set the by `Toplevel = Toplevel` you will get an ambiguous contradiction. The compiler stay confusing if you are sets the `Toplevel` property or the `Toplevel` parameter.

The main problem of this is the `Application.Top` is the `SaveDialog` instead of the `Top` that is set by the `Application.Init`. The `Begin` method should set the `Application.Current` for the `SaveDialog`. Since both frame are different the menu is positioned base on the `SaveDialog` instead of the `Driver.Cols` and `Driver.Rows`. But isn't enough only setting to the driver bounds. It's needed a view, which is `Application.Top` to the positioning work.
