### ISSUE TITLE
`NetDriver` key handling is broken on Windows Terminal v1.18+

### ISSUE THREAD

**Issue by tig** [gui-cs/Terminal.Gui#2745]
To repro simply run UI Catalog and press ESC a few times.

<img width="521" alt="image" src="https://github.com/gui-cs/Terminal.Gui/assets/585482/332d8ee2-0b63-4952-826d-b82c99386d13">

I found this while trying to track down what I broke in #2612.

I kept going back in my commit history to find where the odd behavior I was seeing didn't happen. I eventually just tried v2_develop and discovered this was happening. So I tried it on `develop` too.

**Comment by tig** [comment]
It's actually worse. I wonder if something broke in my version of Windows. Keyboard basically doesn't work at all in the `develop` branch with -usc. 

```
Edition	Windows 11 Pro
Version	22H2
Installed on	‎6/‎11/‎2022
OS build	22631.1972
Serial number	031033494257
Experience	Windows Feature Experience Pack 1000.22658.1000.0
```

**Comment by tig** [comment]
It looks like a recent Windows Terminal problem as I can use ConEmu instead of WIndows Terminal and the keyboard works as expected (mouse doesn't work tho).

Bad:
Windows Terminal Preview Version: 1.18.1462.0

Good:
ConEmu
Windows Terminal Version: 1.17.11461.0

**Comment by tznind** [comment]
What does the call stack look like? `GetKeyCharArray()` is called in multiple places.  If `cki` is null perhaps all we need is a null guard further up?

**Comment by j4james** [comment]
I don't know the code base, so this is just a wild guess, but the code here looks suspicious:

https://github.com/gui-cs/Terminal.Gui/blob/db78fe28bce10fe6ae5d4c6062e8b4ef07f7b8fa/Terminal.Gui/ConsoleDrivers/NetDriver.cs#L198-L201

If you get into that branch, `cki` is going to be set to null, but `isEscSeq` is not reset to false. So the next time `GetConsoleKey` is called, if `consoleKeyInfo.KeyChar` is Esc again, you're assumedly going to enter that branch with `cki` now being null. From there you call `DecodeEscSeq` with null, which in turn calls `GetCharArray` with null.

At least that's what it looks like to me.

**Comment by BDisp** [comment]
@j4james is right. If `isEscSeq` is `true` and the the current `consoleKeyInfo.KeyChar == (char)Key.Esc` then it's only to process a `Key.Esc` and thus the `isEscSeq` must be set to `false`.

**Comment by tig** [comment]
Yep. That's it. Forcing `IsTerminalWithOptions` to always be false enables NetDriver to work in with WT 1.18.

**Comment by BDisp** [comment]
> @j4james is right. If `isEscSeq` is `true` and the current `consoleKeyInfo.KeyChar == (char)Key.Esc` then it's only to process a `Key.Esc` and thus the `isEscSeq` must be set to `false`.

Well, I thinking better about this and I think the code right as is. The above explanation is wrong. When isEscSeq` is `true` and the the `consoleKeyInfo.KeyChar == (char)Key.Esc` then it's only to process a `Key.Esc` and thus the `isEscSeq` can't be set to `false` because the second `Key.Esc` may be only a `Key.Esc` or belong to a escape sequence which will be handle by the first condition, by checking the `Console.KeyAvailable`. If this is `true` and in the next iteration the `consoleKeyInfo.KeyChar != (char)Key.Esc`, then it's a escape sequence. Otherwise, if it's `false` it's a simple `Key.Esc` which will be handled in the second condition where it's the only place where can handle two consecutive `Key.Esc`, one when `consoleKeyInfo.KeyChar == (char)Key.Esc && isEscSeq`, meaning that it only have to processing the `Key.Esc` and two by set the `cki = null` for the first condition process it in the next iteration because it may be only a `Key.Esc` or a escape sequence. If `isEscSeq` is set to `false` in the second condition the escape sequence will not be processed. Also the first condition ensure that only a `Key.Esc` is process if `Console.KeyAvailable` is `false`.

**Comment by tig** [comment]
@BDisp see my latest push to this PR.

There is a bug somewhere that is causing `isEscSeq` to be true with `cki` being null. I've added a defensive check for this as I've not been able to reliably reproduce it in a way that shows me what's causing it. 

Note, I discovered something else that indicates EscSeqUtils may need to be refactored.

If the user presses a key while the terminal is sending an esc sequence (e.g. a '[35` mouse move report), that key info is lost. The result of this is no keystrokes can happen while the user is moving the mouse. 

As we  move to a world where all drivers rely heavily on emitting and receiving escape sequences, we need EscSeqUtils to be very robust and flexible. It works pretty darn good right now (great job!) but it is fragile and brittle. It doesn't help that the documentation for ANSI sequences and all the implementations are so sketchy.

I still haven't figured out what I screwed up in #2612 that has broken netdriver in this regard, FWIW.
