### ISSUE TITLE
Unknown character sequence while resizing terminal

### ISSUE THREAD

**Issue by kacperpikacz** [gui-cs/Terminal.Gui#2865]
**Describe the bug**
If we have TextField focused, while resizing terminal, unknown character sequence is inserted into it.
Second thing is if we have currently focused ListView, the selected item will change.
No matter if we do that by double clicking or by moving corner.

**To Reproduce**
Run UI Catalog

**Screenshots**

https://github.com/gui-cs/Terminal.Gui/assets/76921244/3a6f0e48-014a-4754-88e0-ba7999c003ac

https://github.com/gui-cs/Terminal.Gui/assets/76921244/e75b0add-ca16-44fa-8d6f-975b1558d2c9

**Desktop:**
Silicon Ventura 13.6
Terminal.Gui `develop`

**Comment by BDisp** [comment]
I'm investigating this issue and I'm facing some conflicts on how the behave on `Linux` and `Mac`. The poll function isn't behaving on the same way with various linux distros. At least three situations happen:
1. The `poll` return -1 indicating an error. Even I use it to resize the terminal, sometimes the `LINES` and `COLS` aren't had yet updated and the resize process isn't processed. After some keystroke is detected the `poll` also return -1 and running the `ProcessInput` method the KEY_RESIZE is caught, indicating that a really update was done on the  `LINES` and `COLS` variables. The problem here is the additional keystroke that the `ProcessInput` don't know what to do with it, because the KEY_RESIZE should be returned when the terminal was resized and not when a keystroke was originated (key or mouse).
2. The same as (1) but running the `ProcessInput` method the KEY_RESIZE isn't caught, indicating that the  `LINES` and `COLS` variables weren't yet updated.
3. The `poll` doesn't return at all, which is very grave because the app will not receive any resize signal and will not run the resize process.

The various issue is related on how the `ncurses` is compiled on the various `linux` distros and with the `macOS`. This is a It's a headache.

**Comment by BDisp** [comment]
@kacperpikacz  said on https://github.com/gui-cs/Terminal.Gui/issues/2860#issuecomment-1787387510:
> Can someone take a look at this please?

I'll try to fix this. It's happening on both v1 and v2, right?

**Comment by BDisp** [comment]
@kacperpikacz do you know how to remove the terminal vertical scroll bar on macOS?

![image](https://github.com/gui-cs/Terminal.Gui/assets/13117724/9a04a041-bec3-464f-af5a-cec9ca00e208)

I want to avoid this:

![image](https://github.com/gui-cs/Terminal.Gui/assets/13117724/4b101980-7c0e-4bd2-b1d7-4ef94fa45f7c)

I know this is the alternative screen enabled by the ncurses, but the original still is showing if I scroll up. It's possible to hide the original screen until exit?

**Comment by BDisp** [comment]
@kacperpikacz please test the PR #2951. The only thing I couldn't fix was clear the alternative buffer after exit. On macOS it behaves differently than Linux.
