### ISSUE TITLE
View need a alternative DrawFrame for v2.

### ISSUE THREAD

**Issue by BDisp** [gui-cs/Terminal.Gui#2983]
This is needed for situations where a Border frame isn't possible to use due some complexity scenario.

**Comment by tig** [comment]
@BDisp, as I was working on the fix for #2578 (#2920), I remembered something related to this topic:

The current implementation `Frame.OnDrawContent` uses `LineCanvas` to draw the border.

This was a hacky prototype, IMO. As I noted in the code:

![image](https://github.com/gui-cs/Terminal.Gui/assets/585482/4289314e-dd55-476b-a26b-890fdf23d8c1)

and here: https://github.com/gui-cs/Terminal.Gui/issues/2994

and especially here: https://github.com/gui-cs/Terminal.Gui/issues/2563

![image](https://github.com/gui-cs/Terminal.Gui/assets/585482/bfb0716d-7951-4394-aa1c-b5c1026a5980)

... My vision is that `Border` (in other issues I called it `BorderView`) hosts the following SubViews:

```cs

public class Title : Label {
	// Replace Border with a custom border class that draws the title with 
	// a cool border
}

public class Border : Frame {
	public Border ()
	{
		SetInitialProperties ();
	}

	Line _top;
	Title _title;
	Button _close;
	Line _right;
	Line _bottom;
	Line _left;

	void SetInitialProperties ()
	{
		_title = new Title () {
			X = 1,
			Y = 0
		};
		_top = new Line () {
			X = 0,
			Y = 0,
			Width = Dim.Fill ()
		};
		_close = new Button ("X") {
			X = Pos.AnchorEnd (1), 
			Y = 0,
			Width = 1,
			Height = 1
		};
		_close.Clicked += (s, e) => {
			Application.RequestStop ();
		};
		_right = new Line () {
			X = Pos.AnchorEnd (1),
			Y = 1,
			Height = Dim.Fill ()
		};
		_bottom = new Line () {
			X = 0,
			Y = Pos.AnchorEnd (1),
			Width = Dim.Fill ()
		};
		_left = new Line () {
			X = 0,
			Y = 0,
			Height = Dim.Fill ()
		};
		Add (_title, _top, _close, _right, _bottom, _left);
	}
}
```

(This is just psuedo-code to make my point). For this to work, we still need:

- `Line` needs flushed out to support mouse/keyboard dragging. Right now it's extremely simple. Once done, `LineView` should be nuked.
- A new view `Title` needs to be implemented as a subclass of Label that has the OnDrawContent logic that's currently in `Frame.OnDrawContent` for drawing a title (so it can look like this):
![image](https://github.com/gui-cs/Terminal.Gui/assets/585482/d212c230-9362-4967-9d97-fd11e1cdf8e0)
![image](https://github.com/gui-cs/Terminal.Gui/assets/585482/3b26e1e7-29f8-4866-baae-5e8ba5706727)
![image](https://github.com/gui-cs/Terminal.Gui/assets/585482/5408b5df-28cd-47d6-9f3e-8bb4ad5348fa)

If you get what I'm saying, you'll see that the borders are not actually drawn by Frame at all, but by VIEWS that are subviews of the Frame. 

We may still want a primitive that draws a frame, but not for the reasons you were thinking of.

Make sense?

**Comment by BDisp** [comment]
> If you get what I'm saying, you'll see that the borders are not actually drawn by Frame at all, but by VIEWS that are subviews of the Frame.
> 
I got it laud and clear.

> We may still want a primitive that draws a frame, but not for the reasons you were thinking of.
> 
Yes, we may need.

> Make sense?

Yes it makes much sense because may have situations where we need frame that not belong to the View border and it's outside of a view border. Imagine we want to draw a frame which intersect various views. In this case we can't use the view or sub-views because it's a complex situation.

**Comment by BDisp** [comment]
But I think that the @tznind implementation is enough, right?
