### ISSUE TITLE
0001 for year in Datefield

### ISSUE THREAD

**Issue by petervdpas** [gui-cs/Terminal.Gui#3124]
I can't enter 0001 for year in Datefield... is there something I miss?

**Comment by MaciekWin3** [comment]
Absolutely, you're correct. I attempted to refactor this component to address the issue, but I've encountered some aspects where I'm unsure about the intended behavior. Specifically, there's a field called ShortDate that stores a 2-digit year. While this is convenient, it becomes challenging to distinguish whether the date "06/01/2024" is referring to the year 2024 or 0024. Additionally, I believe it would be beneficial if users could manually specify the date format, as currently, only "MM/dd/yy" and "MM/dd/yyyy" are supported.

I am willing to refactor the code since I've already invested some time in familiarizing myself with the component's codebase. However, I need clarification on the intended behavior to proceed with the changes. @tig can you help?

**Comment by BDisp** [comment]
> Absolutely, you're correct. I attempted to refactor this component to address the issue, but I've encountered some aspects where I'm unsure about the intended behavior. Specifically, there's a field called ShortDate that stores a 2-digit year. While this is convenient, it becomes challenging to distinguish whether the date "06/01/2024" is referring to the year 2024 or 0024. Additionally, I believe it would be beneficial if users could manually specify the date format, as currently, only "MM/dd/yy" and "MM/dd/yyyy" are supported.
> 

With a 2-digit year it's really a challenge to distinguish if the year is referring to the year 0024, 0124, 1924 or 2024. So we can't rely on 2-digit.
The `CultureInfo.CurrentCulture.DateTimeFormat` is also supported which provide much more formats.

> I am willing to refactor the code since I've already invested some time in familiarizing myself with the component's codebase. However, I need clarification on the intended behavior to proceed with the changes. @tig can you help?

I'm preparing a PR to fix only some related issues, but a view like a DatePicker where the user can set it by opening a combo box would be great. Would you are interest on this?

**Comment by MaciekWin3** [comment]
Hey @BDisp, yeah, it sounds great. It will be quite a challenge, but I'll see what I can do. I'll give it a try next week! 😄

**Comment by tig** [comment]
I'm of the opinion that we should leverage as much existing dotnet infrastructure for these Views as possible. The existing implementation is way too bespoke. 

Its well known that date handling is the hardest problem in CompSci 😉

So, big fan of a rewrite that has very little code in it because it uses the work of others smarter than us.

**Comment by MaciekWin3** [comment]
I agree. I was already working on the rewrite of the DateField, but handling two formats, especially the short one (MM/dd/yy), is too confusing. I've already managed to clean up some of the code for the DateField, but in my opinion, if we can get rid of handling the short date format, we can significantly simplify and improve this component. If that's the case, I can prepare a PR with cleanup changes.

Additionally, I've already started working on the DatePicker, and I hope that it will enhance the user experience 😉
