### ISSUE TITLE
Remove `View` and subclass constructors with parameters

### ISSUE THREAD

**Issue by tig** [gui-cs/Terminal.Gui#3171]
I thought we already had an issue for this, but I can't find it. 

We agreed long ago, for various good reasons, to rid ourselves of constructors that take parameters.

With the merging of 

- #3130 

...the biggest reason they existed is now moot: Absolute layout is no longer determined by how the View was constructed.

Anytime you're doing a PR and see the opportunity to delete one of these, please do so. Some will be harder than others. In all cases it is also an opportunity to double-down on unit tests that test initialization.

Also, any methods called from constructors that are currently named `Initialize` should be renamed to `SetInitialProperties` to avoid confusion with `Begin/EndInit`.

## Todo

- [ ] View
- [ ] Button
- [ ] CheckBox
- [ ] ComboBox
- [ ] ColorPicker - Will fix in #2800 
- [x] DateField - Thank you @BDisp!
- [ ] FrameView
- [ ] Label 
- [ ] ListView
- [ ] ScrollBarView
- [ ] ScrollView
- [ ] ContextMenu
- [ ] OpenDialog
- [ ] SaveDialog
- [ ] TextField 
- [ ] TimeField 
- [ ] Toplevel
- [ ] Window

**Comment by dodexahedron** [comment]
So I just wanted to confirm something about this push to eliminate all parameterized constructors.

Have you looked at the IL created by initializers? They're not constructors, and that has various implications for that object instance and the program as a whole. It also has a viral effect on those classes' properties, because properties that _could_ have been get-only if there were an alternate constructor available now must at least have an init setter that is as accessible as the constructor, if it is to be allowed to be set by the consumer. Otherwise, the consumer has to make an additional method call after the initializer, which already represents at least 2 without even setting any properties (the constructor and the initializer anonymous method).

And then, since an initializer is settings things via property accessors, each and every one of the properties that is being set represents _another_ method call, and all of the login in the setter, which now HAS to be consistent and safe before the object is even ready for use.

Those are just the things that immediately occur to me, and I wanted to be sure the scope of the impact of that policy is understood.

What was the reason for that decision anyway?

**Comment by dodexahedron** [comment]
Following up on that comment:

Minimizing constructors, especially if there are a bunch with minimal value, is a perfectly cool thing to do.

And mandating that all View types have a public parameterless constructor _available_ is also a laudable goal, for sure (and that is necessary for certain other things anyway).

_However_, constructors that accept parameters to set things up that are important from the very start are not only convenient to a consumer, they are recommended by the design guidelines for classes, and are _required_ for record classes and any kind of readonly struct that needs to be anything other than its default value.

Forbidding parameterized constructors also makes it a LOT harder to do dependency injection, cooperative cancellation in async code, and plenty of other stuff, and removes the guarantee that would otherwise be available that, when the constructor finishes, the object is now valid and ready to be used. With only empty constructors and without critical properties being marked `required` - which comes with its own set of caveats - it is now harder for a consumer to use the library and automatically increases how many lines of code they need to use it in almost every situation.

**Comment by dodexahedron** [comment]
However, the design strategy of having only parameterless constructors is still _fine_, so long as the entire application treats it correctly.

Note that an object that is created with an initializer exists before it is assigned to the variable or other element that will own it from that point on. This is important _especially_ if the object touches any other object during its constructor. Then you've got references in _those_ objects that can theoretically become invalid if the initializer itself throws an exception but the constructor was successful, which could lead to NREs or ObjectDisposedExceptions later on.

**Comment by dodexahedron** [comment]
Hey @BDisp 

In the code that exists _before_ any changes you may have made so far, I'm noticing that, in some constructors of certain types, such as `ScrollBarView`, there are some patterns such as raising events during the constructor. That's a no-no, and there's going to be significant refactoring of that kind of thing, as I work on #3209.

This is just a heads up for you, as you're doing all that work to get rid of/consolidate constructors. I don't _think_ I need you to do anything specific, when you come across that sort of thing, but I wanted to call it out so you don't spend too much effort trying to make those things work, as-is. If you come across anything like that, could you stick a TODO comment above the line where you found it or something?

Leaving them out entirely is likely to break basically everything, so you'll probably still have to include those method calls, but it will be a great help to me in fixing up the events if you wouldn't mind doing something like that if you remember, when you do come across them. I'll most likely be merging from your branch to my event branch several times, as we're both working on these things, to reduce the number and complexity of changes later on in #3209. And if you don't remember to or don't want to, no big deal. Just a request. :)

**Comment by BDisp** [comment]
> Though, if you _do_ see a way to eliminate those method calls that doesn't require much effort on your part, doing that would be even more appreciated.

There really are some subscriptions to events but not invocations to events. But if these situations really exist, I would prefer that you comment directly in the PR through code review to make the necessary changes or by introducing the TODO comment. Thanks.

**Comment by dodexahedron** [comment]
No problem.

I'll just handle them in my branch, then, since they're not really worth being a blocking review item for this work.

**Comment by BDisp** [comment]
Ok, I also I'm leveraging this branch to add more fixes that are referencing to other opened issues to avoid future hard merge conflicts.

**Comment by dodexahedron** [comment]
Cool.

I think I'm going to just pause most of my work on the event reworking for now, until you're farther along in this work, since the event stuff touches almost everything.

I'll use the time to work on the core concepts behind it, like defining interfaces and stuff like that, which I can then use when it's time to actually implement it all.
