### ISSUE TITLE
TextFormatter.Lines should return a single string.Empty list even with Width or Height equal to zero.

### ISSUE THREAD

**Issue by BDisp** [gui-cs/Terminal.Gui#3224]
I'll fix this in the #3181 because I already have a branch of it on another wip branch.

**Comment by tig** [comment]
> I'll fix this in the #3181 because I already have a branch of it on another wip branch.

Please don't. 

I already have enough merge issues there AND I did a ton of TF fixes in #3202, which I am going to pull out into a separate PR.

**Comment by BDisp** [comment]
I want to use these changes in the #2489. It's almost ready. I'm only struggle when I use the `Pos.Center` on the view location and it's drawing outside the view padding.

**Comment by tig** [comment]
> I want to use these changes in the #2489. It's almost ready. I'm only struggle when I use the `Pos.Center` on the view location and it's drawing outside the view padding.

You'll have to wait until I'm done merging #3181 and #3202. Sorry.

If you want, you can try to take the TextFormatter.cs from #3202 and create a new branch that uses it. However, this requires touching a ton of files because I changed TextFormatter significantly in #3202 (which I shouldn't have done, but I did). In particular I changed `Lines` to be `GetLines ()` because it being a property getter was causing chaos in the debugger.

If you do this, DO NOT apply any code reformatting.

**Comment by BDisp** [comment]
@tig this test is failing:

```cs
	[Fact]
	[SetupFakeDriver]
	public void Button_AutoSize_False_Does_Not_Draw ()
	{
		var btn = new Button {
			AutoSize = false,
			X = Pos.Center (),
			Y = Pos.Center (),
			Text = "Press me!"
		};
		Assert.Equal ("Press me!", btn.Text);
		btn.BeginInit ();
		btn.EndInit ();
		btn.Draw ();

		Assert.Equal ($"{CM.Glyphs.LeftBracket} {btn.Text} {CM.Glyphs.RightBracket}", btn.TextFormatter.Text);
		Assert.Equal ("{Width=0, Height=1}", btn.TextFormatter.Size.ToString ());
		TestHelpers.AssertDriverContentsWithFrameAre ("", _output);
	}
```

The output is:
```
Expected:

 But Was:
          ⟦ Pr
```

This should be really empty because the dimension wasn't already set and `IsInitialized` is `false`. It has a with of 4 because the `SetRelativeLayout`, called by the constructor, is setting the `Pos/Dim` absolute values even without initialize the view. Do you really want to maintain the current behavior?

**Comment by tig** [comment]
> @tig this test is failing:
> 
> ```cs
> 	[Fact]
> 	[SetupFakeDriver]
> 	public void Button_AutoSize_False_Does_Not_Draw ()
> 	{
> 		var btn = new Button {
> 			AutoSize = false,
> 			X = Pos.Center (),
> 			Y = Pos.Center (),
> 			Text = "Press me!"
> 		};
> 		Assert.Equal ("Press me!", btn.Text);
> 		btn.BeginInit ();
> 		btn.EndInit ();
> 		btn.Draw ();
> 
> 		Assert.Equal ($"{CM.Glyphs.LeftBracket} {btn.Text} {CM.Glyphs.RightBracket}", btn.TextFormatter.Text);
> 		Assert.Equal ("{Width=0, Height=1}", btn.TextFormatter.Size.ToString ());
> 		TestHelpers.AssertDriverContentsWithFrameAre ("", _output);
> 	}
> ```
> 
> The output is:
> 
> ```
> Expected:
> 
>  But Was:
>           ⟦ Pr
> ```
> 
> This should be really empty because the dimension wasn't already set and `IsInitialized` is `false`. It has a width of 4 because the `SetRelativeLayout`, called by the constructor, is setting the `Pos/Dim` absolute values even without initialize the view. Do you really want to maintain the current behavior?

First, you need to ask "What, really, is the purpose of this test? What *precisely* is it testing at a unit level? I deleted this test because I moved what it was testing to where those tests belonged (Layout and Text). 

There is a bug here though. Let's decode it.

`SetRelativeLayout` is called because the constructor (actually the `View` constructor) sets `Text`, and the `Text` setter ends up calling `SetRelativeLayout`:

![image](https://github.com/gui-cs/Terminal.Gui/assets/585482/6b8edd08-2074-42c3-939c-c5f8a1f8566a)

`SetRelativeLayout` gets called again when `Button` sets `TextAlignment` in its constructor:

![image](https://github.com/gui-cs/Terminal.Gui/assets/585482/14a6e1f9-fd9e-458e-9b97-5e2aa7d31fd8)

And again when `Height` is set:

![image](https://github.com/gui-cs/Terminal.Gui/assets/585482/2190519f-443d-4577-b725-2b2116d7015f)

And AGAIN when `AutoSize` is set:

![image](https://github.com/gui-cs/Terminal.Gui/assets/585482/ded973e7-0c0b-49d7-99fa-2d583254d986)

etc...

Finally, when `Text = "Press me!" happens:

![image](https://github.com/gui-cs/Terminal.Gui/assets/585482/51f4fdbd-6762-4925-9b10-59f93a7ff6dd)

Before `BeginInit` is called:

![image](https://github.com/gui-cs/Terminal.Gui/assets/585482/286d271f-583c-4a66-91e0-e0164dfafb0f)

As you note this is clearly wrong, giving `AutoSize == false`. 

The question is, what is right (for Button)? 

1) `0, 0`
2) `0, 1` 
3) `4, 1` (current behavior)
4) `13, 1` (4 + "Press me!") 

I want to view this through the lens of `Dim.Auto` existing (and `View.AutoSize` being nuked). I think, by default, `Button` would be set like this:

```cs
Width = Dim.Auto ();
Height = 1;
```

If someone were to set `Width` to some other value, the button would be that Width.

All that said, I think the TEST is buggy: Setting `AutoSize = false` invalidates `Height` and `Width`. The test never sets `Height` and `Width` and thus they are indeterminate.

This is correct:

```cs
[Fact]
[SetupFakeDriver]
public void Button_AutoSize_False_Does_Not_Draw ()
{
    var btn = new Button
    {
        AutoSize = false,
        X = Pos.Center (),
        Y = Pos.Center (),
        Height = 1,
        Width = 0,
        Text = "Press me!"
    };
    Assert.Equal ("Press me!", btn.Text);
    btn.BeginInit ();
    btn.EndInit ();
    btn.Draw ();

    Assert.Equal ($"{CM.Glyphs.LeftBracket} {btn.Text} {CM.Glyphs.RightBracket}", btn.TextFormatter.Text);
    Assert.Equal ("{Width=0, Height=1}", btn.TextFormatter.Size.ToString ());
    TestHelpers.AssertDriverContentsWithFrameAre ("", _output);
}
```

**Comment by BDisp** [comment]
Closing this because the `Button` is a special view that overrides the `UpdateTextFormatterText` method and thus set a minimal sie of 4 for the brackets and spaces if no width is set at object initializer. Setting only the width equal to zero, as the Button already sets the height on the constructor, the test pass. Thanks @tig.
