### ISSUE TITLE
Work around VS2022 17.10.0 Preview 1.0 breaks collection expression for certain types

### ISSUE THREAD

**Issue by tig** [gui-cs/Terminal.Gui#3293]
See https://developercommunity.visualstudio.com/t/VS2022-17100-Preview-10-breaks-collec/10596187

Until this is fixed, we should work around it by changing the collection intializer in

\UnitTests\Drawing\ColorTests.ParsingAndFormatting.cs:

https://github.com/gui-cs/Terminal.Gui/blob/eeced7e7727bae0e07db3dfd8938340cd10eadac/UnitTests/Drawing/ColorTests.ParsingAndFormatting.cs#L107C1-L115C14

**Comment by dodexahedron** [comment]
A thought, for cases that might come up where it's _not_ a bug in VS.VNext (so not applicable to this one):

Do keep in mind that sometimes broken behavior in a pre-release VS version may be because of changes in .net 9, c# 13, or actual fixes to bad behavior in the current stable version.

Or, they may be buggy behavior in the new version.

So it's important to be sure the end result of a change for that is fully analyzed, so we don't accidentally make a change that has a subtly broken behavior or omission for the latest .net LTS release we support.

What _is_ relevant to this one is that last part. That change isn't 1-to-1 with the previous code, because the collections aren't the same.
