### ISSUE TITLE
A view where `CanFocus` is true must be able to set focus on click.

### ISSUE THREAD

**Issue by BDisp** [gui-cs/Terminal.Gui#3310]
On the same way that tabbing can set focus a view which `CanFocus` is true, then clicking on a view can also set the focus. I think in the `ViewMouse.cs` should be like this:

```cs
    protected bool OnMouseClick (MouseEventEventArgs args)
    {
        if (!Enabled)
        {
            return true;
        }

        MouseClick?.Invoke (this, args);
        if (args.Handled)
        {
            return true;
        }

        if (!HasFocus && CanFocus)
        {
            SetFocus();
        }

        return args.Handled;
    }
```

_Originally posted by @BDisp in https://github.com/gui-cs/Terminal.Gui/issues/3306#issuecomment-1985650742_

**Comment by BDisp** [comment]
Fixes #3310 (https://github.com/gui-cs/Terminal.Gui/pull/3254/commits/fc0f25e3316d3195e07570cd76a3224324d10d24)

**Comment by dodexahedron** [comment]
A note about events, when anybody works on them in any significant way in the future:

The wrapper methods should have a minimum of the same signature as the event, unless the wrapper is private. Otherwise, the reference in `sender`, while it is still the same object, is passed as whatever `this` is, at the callsite.

While that's not necessarily _broken_, and is still technically completely fine, it does mean that a handler that cares about it will receive that type, even if it's still legal to cast it to something else (so, `View` in most cases). Again, that's fine but makes a bit more work for the runtime whenever `sender` is actually used, and also makes certain static analysis cases at design time a little less useful, such as when it can definitively know that the incoming value is a more specific type, enabling a few inspections in some cases but also enabling additional optimizations at run-time by the JITer, which is even more impactful if the sender happens to be a generic type.

Aside from that, the type declaring the event and thus the one invoking the delegate may also have use for knowing who/what asked to raise it, now or in the future.

**Comment by BDisp** [comment]
The view only get the focus if the `MouseClick` event wasn't handled by the user. If it return false I think it doesn't propagate to another view, unless a derived class is handle the mouse. But one of the first behaviors they have is normally focus the view, so I think is acceptable.
