### ISSUE TITLE
v2: Application.Top is null

### ISSUE THREAD

**Issue by fergusonr** [gui-cs/Terminal.Gui#3389]
Somewhere between 2.0.0-pre.636 and 2.0.0-pre.735 Application.Top is no longer initialized after Init()

```CSharp
static void Main()
{
	Application.Init();

	if (Application.Top == null) // 2.0.0-pre.735 bug? Always null
		return;
```

**Comment by tig** [comment]
> Somewhere between 2.0.0-pre.636 and 2.0.0-pre.735 Application.Top is no longer initialized after Init()
> 
> ```cs
> static void Main()
> {
> 	Application.Init();
> 
> 	if (Application.Top == null) // 2.0.0-pre.735 bug? Always null
> 		return;
> ```

This was a breaking change introduced to fix

- [#application.top](https://github.com/gui-cs/Terminal.Gui/issues/3313)

Apologies for the churn, but this change was important to make the library more robust.

The fix is for apps to do one of the following:

1) `var top = new MyToplevel(); Applicaiton.Run(top).Dispose();`
2) `var top = Application.Run<MyToplevel> ().Dispose();`
3) `Application.Run().Dispose();`

**Comment by tig** [comment]
Closing as by-design.
