### ISSUE TITLE
Mixing signatures for ScreenToX between `int` and `Point`

### ISSUE THREAD

**Issue by tznind** [gui-cs/Terminal.Gui#3460]
`ScreenToContent` uses `Point`
`ScreenToViewport` uses `int`,`int`
`ScreenToFrame` uses `int`,`int`

![image](https://github.com/gui-cs/Terminal.Gui/assets/31306100/08c81ef0-1f81-454b-9b55-546196db77d7)

Is it possible to please standardize these? or is there a reason they are not consistent. 

It makes debugging screen pointer issues difficult if you are trying to switch between the two methods to see which is more correct.

**Comment by tig** [comment]
I agree. 

Your preference? `Point` or two `int`?

**Comment by tznind** [comment]
I think point makes most sense as that is the return type too.

Also eliminates any chance that someone gets the args the wrong way around
(I.e because there will only be 1).

But happy to be persuaded otherwise if there is any performance or elegance
factor others can see.

**Comment by dodexahedron** [comment]
It's pretty common in a lot of UI frameworks to expose both a coordinate pair (so Point, here) as well as the component coordinates, as ints, with the actual value being stored in the Point and the ints just retrieving that coordinate from the point for `get` and mutating the Point on `set` (it's immutable, so that means re-assignment - use the `with { X = value; }` method for that).

I'd suggest, to help with this sort of thing in general, and to _force_ us to be consistent (plus for testing and other benefits), an `IPositionable` or otherwise appropriately named interface be created that has exactly those 3 properties, with both get and set accessors on all 3.

Implementations in types declaring the interface should store just the Point as a private field and the properties do the above operations.

**Comment by dodexahedron** [comment]
Oh also, a pretty important thing about immutable types as properties:

The `get` accessor for any property that is an immutable type should be `readonly get` instead of just `get`, so that the compiler will disallow attempts to write to the returned item - which is important because it's a copy, as properties cannot return by reference.

**Comment by tig** [comment]
See https://github.com/gui-cs/Terminal.Gui/pull/3461

**Comment by tig** [comment]
Note, as part of

- #3029

... we need to change `MouseEvent` to hold a `Point`

**Comment by dodexahedron** [comment]
Emphatic agree on that one. 👍
