### ISSUE TITLE
New nuget packages not shipping on merge

### ISSUE THREAD

**Issue by tznind** [gui-cs/Terminal.Gui#3470]
**Describe the bug**
Publishing of pre packages from v2_develop has stopped working with error:

```
/home/runner/work/_temp/729717ff-0270-463a-80f6-2cbe70f5b9be.sh: line 2: Import-Module: command not found
```
For example, see [this build](https://github.com/gui-cs/Terminal.Gui/actions/runs/9045144915/job/24854578754)

**Comment by dodexahedron** [comment]
You need to add powershell to the environment if you want to build it in that fashion.

Otherwise you can just dotnet build on them in sequence.

I'd say add powershell. There are other useful things we can do.

**Comment by dodexahedron** [comment]
Though of course the `dotnet build` way is less to figure out if you want a quick solution.

**Comment by dodexahedron** [comment]
Or...

Another option is to add a configuration to the solution intended for CI builds that doesn't exclude compiling the analyzer library.

That might actually be the _best_ thing to do anyway, because we can also have it not do anything we don't need it to do a lot easier that way.

**Comment by dodexahedron** [comment]
That method also meshes well with having other build targets or msbuild project files used for CI builds.

When you do that, then people don't see it in VS and wonder WTF it is, and it just gets used in combination with the solution.

So many options. And most aren't even mutually exclusive. 😅

**Comment by tig** [comment]
Fixed. Sorry about that.

**Comment by dodexahedron** [comment]
Would you like me to shift back to doing the stuff I was talking about in the thread for enhancing the build process, instead, now that I'm no longer actively doing anything to @BDisp's Region branch til he finishes with his improvements?

As part of the github workflow improvements, making the runners fork-friendly (beyond just suppressing them), so that people can test without the noise of failed deployments and such will be a good thing. This issue and the others directly related to the gh build runners can be caught before merge time if that's more friendly. And that actually might simply come down to a checkbox in the project, but they've been upgrading and changing things a lot so I'll have to go make sure that's not different from the last one I had to set up, a few months ago.

**Comment by tig** [comment]
I'm game for that. 

I've gotten this projects CI/CD working only because I am good at copy pasting, not knowledge. 

I can't even spell YAML.

**Comment by dodexahedron** [comment]
~~YAML~~  YAML

FTFY. 😅 

To be fair, the documentation is really bad. It very rarely says enough to actually understand something.

And I've never seen an official schema, either. The links that look like they might lead to one don't go to one. All I want is a schema! Learning what can go where is a chore with their docs.
