### ISSUE TITLE
v2 Pos classes need to support interrogation for TGD

### ISSUE THREAD

**Issue by tznind** [gui-cs/Terminal.Gui#3482]
**Executive Summary**
It is no longer possible to know important things about a given Pos because of the use of [primary constructors](https://learn.microsoft.com/en-us/dotnet/csharp/whats-new/tutorials/primary-constructors), whose parameters are innaccessible through reflection.

**Detail**
Consider `Pos.PosView` (aka relative to)

***V1***
In v1 fields were side and View
- These were accessed via reflection in TGD

For example
```csharp
    public static bool IsCombine( [NotNullWhen( true )] Pos? p )
    {
        if ( p == null )
        {
            return false;
        }

        return p.GetType( ).Name == "PosCombine";
    }
```
Also
```csharp
  var fTarget = posView.GetType().GetField("Target") ?? throw new Exception("PosView was missing expected field 'Target'");
  View view = (View?)fTarget.GetValue(posView) ?? throw new Exception("PosView had a null 'Target' view");
```

***V2***
In v2 internals are now visible to TGD (yay!) so can do like

```
if(p is Pos.PosCombine pc)
{
...
}
```

However there are some changes to use [primary constructors](https://learn.microsoft.com/en-us/dotnet/csharp/whats-new/tutorials/primary-constructors)  e.g.

```csharp
internal class PosView (View view, Side side) : Pos
```
_v2 code for PosView_

Since Side is no longer a field, we cannot read it in TGD.  If in the debugger we examine the source for the object we get that it has this secret hidden field thats super sketchy.

```csharp
        [CompilerGenerated]
        private Side _003Cside_003EP;

        public readonly View Target;

        public PosView(View view, Side side)
        {
            _003Cside_003EP = side;
            Target = view;
            base._002Ector();
        }
```

**Fix**
Fix will be to expose as `public readonly` the constructor properties e.g. like Side 

This will enable the TGD to read them and support its UIs for designing/editting the position stuff is at.

```diff

    internal class PosView (View view, Side side) : Pos
    {
         public readonly View Target = view;
+        public Side TargetSide => side;
```

**Comment by tznind** [comment]
Given that these classes are `internal`, is there any issue with making all the private fields public?

Also for those that are currently private e.g. `_factor` for `PosFactor`?

If public is acceptable then what is the best way to do that
- `public readonly` field (Note that doing this for side somehow causes [CS9124](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/constructor-errors?f1url=%3FappId%3Droslyn%26k%3Dk(CS9124)#primary-constructor-declaration) )
- public property (e.g. as above)
- other?

**Comment by dodexahedron** [comment]
Something you may want to check out that avoids manual reflection and is super speedy for member access:

[`UnsafeAccessorAttribute`](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.unsafeaccessorattribute?view=net-8.0)

As for addressing the problem, though:

Why is direct access to the fields necessary?

**Comment by tznind** [comment]
> Why is direct access to the fields necessary?

In editor you add a view and set it X pos relative to another

You save and get .Designer.cs file

You close and reopen

Editor compiles .Designer.cs into in memory assembly and stamps out an
instance of the view (to the main editing area).

You right click view and edit the X field

Designer looks at value of X on the  instance of the view and shows that in
PosEditor (i.e. tell user the current value)

Hence for any Pos the designer needs to be able to work out what kind it is
and what its settings are.

**Comment by dodexahedron** [comment]
Gotcha.

I happened to update my previous reply like... Seconds after you replied just now, with a little bit more info, btw.

**Comment by tznind** [comment]
Ah I see now!

The problem is that there are no accessors for PosView Side or the percent
one.

**Comment by dodexahedron** [comment]
And as for the basic issue of how to figure it out...

The nested types are unfortunate.

Really should be an inheritance hierarchy.

**Comment by tig** [comment]
The right thing to do here is consider Designer as a perfectly valid app and expose things it needs via a suitably designed `public` API.

I'm knee deep in `DimPos.cs` right now and have been fighting with myself over this very topic for different reasons.

- #3469 

I wasn't going to tackle solving this before I saw this Issue. Now I am. Stay tuned.

**Comment by tig** [comment]
This is the PR that will address this:

- #3480

**Comment by dodexahedron** [comment]
> The right thing to do here is consider Designer as a perfectly valid app and expose things it needs via a suitably designed `public` API.
> 
> I'm knee deep in `DimPos.cs` right now and have been fighting with myself over this very topic for different reasons.
> 
> * [`Dim.Auto (DimAutoStyle.Text)` confuses `TextFormatter` when `Width` is absoulte and `Height` is auto #3469](https://github.com/gui-cs/Terminal.Gui/issues/3469)
> 
> I wasn't going to tackle solving this before I saw this Issue. Now I am. Stay tuned.

I initially agreed with the _concept,_ but the implementation in the PR doesn't support the concept - it just special-cases TGD, which is kinda antithetical to the goal. `internal` isn't public, and is essentially just a kludge when combined with InternalsVisibleTo.

It is also purely namespace-based.\
Any code, in any application, anywhere, at any level of inheriting references to TG, if it is declared in a namespace specified in InternalsVisibleTo, sees internals.

This is special-casing things for TGD (which is fine, IMO, in more limited ways, since it IS part of the org), not creating a proper public API surface.

The [UnsafeAccessor] method of accessing otherwise non-visible members is "easier," _significantly_ faster than even cached reflection, and - most importantly - is done by and is the sole responsibility of the application trying to break the rules of encapsulation (which is legitimate when it needs to be done, like in TGD).

### BUT, back to the concept of the public API being proper and correct and complete...

I'll be blunt as always, so bear in mind none of this is aimed at any _person_ - just code, concepts, guidelines, conventions, etc:

I gotta point to our [stated public API tenets for V2](https://github.com/gui-cs/Terminal.Gui/blob/main/CONTRIBUTING.md#public-api-tenets--guidelines). In particular, item number 1, with overlap to item 4.

It's against guidelines and non-standard to be using nested types, like that, with no actual need to do so (which there isn't - it's a smell).

I wish I had not deleted the branch I made several months ago where I split them out into a proper inheritance hierarchy, mostly for proof that it's not as scary to do as one might assume. But it became very out of date very quickly, and was still before the merge strategy was fixed, so it was more work to fix than to just do again. But I guess if I had kept it, it wouldn't be helpful anyway for those reasons. My thinking at the time was things were still moving very quickly and the API was rapidly changing, so that kind of change at that point would have been difficult to resolve across all the open branches and whatnot.

### What's the idiomatic C# and dotnet way to do it and what adheres to the concept of making the public API "good?"

At the most basic level: All of those Pos and Dim types should be public, not private or internal.

You should ***never*** lie to your API consumer about the type of an object, in a way that they are incapable of accessing, yet have material impacts on behavior, which those very much do. Nobody should have to run to the TG code to find out why what looks like one type of object can act a few different ways and what the specifics of that behavior are.

But for a proper, well-designed API, there should also be interfaces all over the place that aren't here. Those all by themselves help address several of the growing pains everyone has run into as the body of code has grown larger and larger.

This will keep getting a bit farther and farther off of the original point, so I'll cut off here.

But yeah - I can't support that PR as-is and really do think that those types need to be split up appropriately. It's just too black-boxy, has unintended costs due to the nested types, and is an antipattern. 🤷‍♂️

**Comment by dodexahedron** [comment]
As far as TGD goes, providing proper interfaces would allow @tznind to access a lot more than he currently can, _without reflection or [UnsafeAccessor]_, which would be even better for him and for consumers of TG, TGD, and TG apps designed in TGD.

**Comment by dodexahedron** [comment]
Shifting gears to a completely different question for you @tznind:

Are you watching the stuff in .net 9.0 around dynamic persistent assembly creation? 😱  That stuff looks awesome.

**Comment by dodexahedron** [comment]
Oh, and _back_ to the nested types gripe fest:

Always remember that dotnet and the CLR are bigger than just C#.

Nested types are already not the best thing to be doing in C#, but they range in compatibility with other languages from mostly the same to broken to not possible.

Even within c#, "simple" things like the accessibility rules for nested types create a form of coupling that normally doesn't exist with normal types, and a change one place can have non-obvious fallout elsewhere. That's bad.

One of the few examples of acceptable use of nested types is when a type needs to create and use instances of a type nested within itself and is the ONLY type that it matters to, as _purely_ an implementation detail.

That's not the case with these.

**Comment by dodexahedron** [comment]
BAH.

Ok ignore literally all of that, because I was totally mis-reading the diffs.

My bad.

I'm pulling it down to look at it in-situ, now, instead of trying to make sense of the diffs.

If you totally already took care of that in this PR you are my hero. ❤️

**Comment by dodexahedron** [comment]
Well.. Except for the dynamic persisted assemblies, for you, @tznind 

That looks like a perfect thing for you, down the road.

**Comment by dodexahedron** [comment]
It's like Christmas in May!

I less than three you, @tig , for biting the bullet and doing this. :)

It's a big and difficult to review PR, so I'm going to compare locally in better tools than the github web UI once you're finished with it.

I do see some things we can and maybe should do, but they shouldn't be part of this one. It should probably be as isolated to the refactor of the type hierarchy as reasonably possible.

**Comment by dodexahedron** [comment]
But, related to one bit I mentioned: We should definitely look at removing any InternalsVisibleTo dependencies between TG and TGD that remain, as well, in support of the goal.
