### ISSUE TITLE
ScrollView.ContentSize no setter

### ISSUE THREAD

**Issue by tznind** [gui-cs/Terminal.Gui#3501]
**Describe the bug**

TGD allows you to design properties on views.  For ScrollView this includes `ContentSize`.  This functionality relies on both a public `get;` and `set;`

It seems the setter no longer exists for this property.  Instead there is a method.

![image](https://github.com/gui-cs/Terminal.Gui/assets/31306100/5a779190-7079-47a4-9c17-14934e925e20)

Is it possible to revert this back to being a property?

```
yield return this.CreateProperty(nameof(ScrollView.ContentSize));
```
_TGD code that advertises ContentSize as designable_

**Comment by tig** [comment]
First, `ScrollView` is going away so please just #ifdef around this specific issue until

- https://github.com/gui-cs/Terminal.Gui/issues/2489

is done.

However, needing to set the new `View.ContentSize` via a property setter is news to me. I changed it to `SetContentSize ()` because the logic of dealing with `ContentSize_set` side-effects was hairy and it seemed to make more sense for it to be an explicit set method.

Happy to change this back, but I'd like to makes sure I understand why first. 

I also want to make sure you fully grok the new content scrolling ability built in to `View` as well. Do you?

**Comment by tznind** [comment]
> If you're not sure, I spent a ton of time on API docs and conceptual docs:

I will take a look into this, at the moment I was just trying to get all the tests passing and the ScrollView ones are currently broken.

If all View become scrollable then its probably best to leave them in and try to port the tests to a use case where a `View` is marked scrollable somehow in the designer.

**Comment by tig** [comment]
The problem is I've enabled two scenarios and they are fighting with eadch other. I need to rethink this.

1) Virtual content area/Scrolling - ContentSize being explicitly set means the view's content size independent of `Viewport.Size` - Scrolling is enabled.
2) AutoSize based on ContentSize - ContentSize being explicitly set means if `Width` or `Height` is `Dim.Auto (DimAutoStyle.Content)`, the autosize mechanism will use ContentSize to size the view.

I'll get you a PR ASAP that unblocks you by reverting to having `set_ContentSize`  work.
