### ISSUE TITLE
Change default `Appliation.QuitKey` to `Esc` from `Ctrl-Q`

### ISSUE THREAD

**Issue by tig** [gui-cs/Terminal.Gui#3516]
Ctrl-Q is non-standard across all platforms and un-intuitive. 

Esc is much more natural.

The change simply requires changing this line in `\Terminal.Gui\Resources\config.json`:

![image](https://github.com/gui-cs/Terminal.Gui/assets/585482/eaf9a476-5167-48a6-8430-2bd6842592c3)

And updating some unit tests.

**Comment by dodexahedron** [comment]
Escape is also not exactly a hard standard, and is in fact used by some software as what it is - the escape key, not a "quit application" key.

Even in Unixy systems, it's all over the place.

Three of the most commonly used utilities, emacs, vi, and nano, all have different means of exiting.

As such, I think it's fine we default to ctrl+Q, as it's unlikely to be otherwise bound beyond the scope of the application using TG.

**Comment by tig** [comment]
OCGV has used esc for 4 years with tons of Mac and Linux users. None have complained.

I think the default quit key should be esc on all platforms. With CM it is trivial for users to change this if they don't like it.

**Comment by dodexahedron** [comment]
It would be nice if everyone would just adopt one.

My main opinion on it is basically it ain't broke, so don't fix it.

But it's also unimportant for exactly this reason, so it's not worth more back and forth if you want to change it regardless 🤷‍♂️ :

>it is trivial for users to change this if they don't like it.

**Comment by BDisp** [comment]
I absolutely agree changing the current `Ctrl+Q` to Esc or any other program that does not interact with any other program, especially `VS2022` or `VSCode`, where `Ctrl+Q` is intercepted by any of the aforementioned, instead of the developed application, if we are using an integrated terminal. I know it is possible to change the shortcut for these applications but it would be better to change the `Terminal.Gui` shortcut.

**Comment by dodexahedron** [comment]
Yeah I think we're all aligned on this, more or less.

I did run into am interesting one a few days ago that made me think about it again.

But the fact thst it is trivially configurable both on code and configuration files really just solves the problem entirely, so it's cool whatever it ends up being, within reason . 👍

Still needs to be loudly documented of course.

I'd even suggest that, in samples and "getting started" type documentation, we repeat what the default quit key is, perhaps in a short bulleted list of important concepts for the given doc/sample, plus a simple link to the config docs, so it's dead simple for a consumer, and any potential "how do I exit‽" issues posted can be closed with a well-deserved "RTFM" linked to any one of those. Plus that would boost their ranking in search engines. 👌

**Comment by dodexahedron** [comment]
Besides, it's already one of the oldest jokes in terminal-land that there are users out there who have been stuck inside vi for years, because they can't figure out how to exit. That'd be a fun little easter egg kind of reference to subtly make somewhere in docs or code comments. 😅
