### ISSUE TITLE
DimAuto equality

### ISSUE THREAD

**Issue by tznind** [gui-cs/Terminal.Gui#3521]
**Describe the bug**

Regarding equality of DimAuto.  The following test fails

```csharp
    [Test]
    public void TestEquality()
    {
        var a = new DimAuto
        {
            MaximumContentDim = null,
            MinimumContentDim = 1,
            Style = DimAutoStyle.Auto
        };
        var b = new DimAuto
        {
            MaximumContentDim = null,
            MinimumContentDim = 1,
            Style = DimAutoStyle.Auto
        };
        ClassicAssert.IsTrue(a.Equals(b));
        ClassicAssert.IsTrue(a.GetHashCode() == b.GetHashCode());
    }
```

Notice also that even the basic case fails:

```csharp
    [Test]
    public void TestEquality()
    {
        var a = Dim.Auto();
        var b = Dim.Auto();
        ClassicAssert.IsTrue(a.Equals(b));
        ClassicAssert.IsTrue(a.GetHashCode() == b.GetHashCode());
    }
```

Percent does not behave this way, it supports Equals

```csharp
    [Test]
    public void TestEquality3()
    {
        var a = Dim.Percent(32);
        var b = Dim.Percent(32);
        ClassicAssert.IsTrue(a.Equals(b));
        ClassicAssert.IsTrue(a.GetHashCode() == b.GetHashCode());
    }
```

**Comment by tznind** [comment]
Also not sure if `==` operator should be working for these.  I see even for `Percent` that does not supported.

**Comment by tig** [comment]
I meant to add such a test. All `Pos`/`Dim` classes should support equality testing and should have unit tests.

`DimAuto` is stil not fully baked, particularly use-cases involving `DimAutoStyle.Content`, FWIW.

**Comment by dodexahedron** [comment]
Oh something important about equality, in particular for these types:

I'd really like to turn them into record structs, if possible, because they are values and making the compiler treat them as such will help avoid inconsistencies in treating them as value or reference.

However, that will make it illegal to define operator== and operator!=, as they are defined as all field value equality generated by Roslyn entirely and not able to be overridden.

Equals isn't operator== though and it can be overridden in record structs.

If it turns out to be too difficult to make them record structs, then record and struct are the next two choices, but that's a bridge to cross if/when we get to it.

**Comment by dodexahedron** [comment]
🥳 

Nice
