### ISSUE TITLE
Disable borders on a MenuItem

### ISSUE THREAD

**Issue by luizfernandonb** [gui-cs/Terminal.Gui#3543]
**Describe the bug**
Can't disable borders for a `MenuItem`

**Expected behavior**
The name "Close" without the white border around it

**Screenshots**
![image](https://github.com/gui-cs/Terminal.Gui/assets/42288418/aaabd758-d851-4d15-9b55-b3f0939f7184)

**Additional context**
I tried every way I could find and managed to do it, nothing disabled it, if I'm doing it wrong, I apologize

**Comment by tznind** [comment]
I don't think this can currently be controlled.  Ordinarily the way to adjust draw behaviour is to subclass but the menu draw logic makes heavy use of private and internal variables so I do not think it is possible.

Possibly in v2 something could be possible like leveraging Border.Thuckness @BDisp?.

**Comment by BDisp** [comment]
> I don't think this can currently be controlled. Ordinarily the way to adjust draw behaviour is to subclass but the menu draw logic makes heavy use of private and internal variables so I do not think it is possible.
> 
> Possibly in v2 something could be possible like leveraging Border.Thuckness @BDisp?.

Really the only possibility for this to happen is only in v2. The reason why the border is not configurable is because when joining the edges it is not possible to automatically insert the tees and that is why it is being manipulated internally in the Menu. But with some work this may be possible to achieve, just like I did with `TabView`, where there may or may not be borders on the tabs, but I'll say right away that this is very laborious and monotonous :-)

**Comment by luizfernandonb** [comment]
Do I leave this issue open so it can be marked for implementation in v2?

**Comment by tig** [comment]
It's already supported in v2.
