### ISSUE TITLE
`Button` with `ShadowStyle.Opaque` is broken

### ISSUE THREAD

**Issue by tig** [gui-cs/Terminal.Gui#3583]
Somewhere in the last few PRs (probably the event one), I broke the 3D effect of `Button`::

![JMshjZv 1](https://github.com/gui-cs/Terminal.Gui/assets/585482/74403920-befd-4d93-aea4-609199e340dd)

**Comment by BDisp** [comment]
The only way to prevent code from breaking is to use colored assertions in unit tests. But you seem to avoid them.

**Comment by tig** [comment]
This one could have been caught without a color test. 

But, you're right I avoid the color tests because I find the api extremely confusing.

**Comment by BDisp** [comment]
> This one could have been caught without a color test.
> 
> But, you're right I avoid the color tests because I find the api extremely confusing.

Initially it seems very confusing but if you focus and remember that you just have to create an Attribute array with the colors that your test will use and create a string representing a rectangle with the respective array indexes of expected colors, it becomes much more easy.
Later, if there is a definitive change in the behavior of the colors in the respective test, then you will have to change it in the test to reflect these changes.
It's the only way to test the colors because the colors are not echoed to the console like when running normally.

**Comment by tig** [comment]
> It's the only way...

There is very rarely only one way to do something. Are you sure we couldn't engineer something different?

**Comment by BDisp** [comment]
> There is very rarely only one way to do something. Are you sure we couldn't engineer something different?

I don't think so. We can only map the colors to return another type of object, but we also need to make sure they are being output in the correct row and column, so the mapping should only return one character of length one or two for wide characters, for each color. You could just use the color and position return, which is what it actually does, and assert these values, but it would be much more difficult to check whether the values ​​are completely in the correct values ​​and positions. Therefore, a string that contains the characters that represent the colors in the correct positions is much more advantageous.

0 = Color0
1 = Color1

0000000000
0111111110
0000000000

We immediately obtain the information that Color1 is between positions (1,1) and (1,8).

But I'm curious if it's really possible to use another, more direct approach to testing colors in a more real and direct way.
