### ISSUE TITLE
`FileDialog` has a non-standard/non-intuitive keyboard nav model

### ISSUE THREAD

**Issue by tig** [gui-cs/Terminal.Gui#3696]
```cs
        // BUGBUG: This TabOrder is counter-intuitive. The tab order for a dialog should match the
        // order the Views' are presented, left to right, top to bottom.
        // Determines tab order
        Add (_btnToggleSplitterCollapse);
        Add (_tbFind);
        Add (_spinnerView);
        Add (_btnOk);
        Add (_btnCancel);
        Add (_btnUp);
        Add (_btnBack);
        Add (_btnForward);
        Add (_tbPath);
        Add (_splitContainer);
```

**Comment by tznind** [comment]
Do you want me to delete the `NavigateIf` stuff?

Maybe it doesn't make sense anymore but original idea was for the cursor keys to move to the next logical area of 'primary' views. While the less used buttons (back, up and expand/collapse tree view) had to be tabbed to).

Idea being if you enter a folder path then press down you can cycle the selected files rather than it just moving focus to the Up arrow button.


![image](https://github.com/user-attachments/assets/492d31cc-8cee-4f45-a01d-116431d8ca7a)
_Primary views that most users will interact with in green, secondary views in red that are less often pressed_

**Comment by tig** [comment]
I'd much rather use the UI requirements for `FileDialog` drive the built-in/default focus model than have `FileDialog` do a bunch of complex stuff. 

In v2 (now...totally willing to adjust):

(From https://gui-cs.github.io/Terminal.GuiV2Docs/docs/navigation.html#keyboard-navigation):

![image](https://github.com/user-attachments/assets/f09c1e06-460c-4019-a042-affdf451c3ef)

In v1 this was totally inconsistent.

**Comment by tznind** [comment]
Ok I will delete all the bespoke logic and see where it gets us.
