### ISSUE TITLE
Remove dependency on ustring

### ISSUE THREAD

**Issue by migueldeicaza** [gui-cs/Terminal.Gui#92]
We might need to introduce string overloads

**Comment by ebekker** [comment]
Isn't the more functional approach in F# to pipe the value, such as `"foobar" |> ustring`?

**Comment by jpierson** [comment]
@ebekker, that definitely looks valid as long as `ustring` is not a constructor but whether it's more functional or not I think is subjective. I typically use the pipe forward operator for larger chains of transformations.

**Comment by migueldeicaza** [comment]
Yeah, I think I might need to make ustring just an internal API, and an optional API everywhere :-(

**Comment by asik** [comment]
You run into the same issue using SharpDX. That's why I always define an implicit conversion operator:

`let inline (!>) (x:^a) : ^b = ((^a or ^b) : (static member op_Implicit : ^a -> ^b) x) `

Then you just write `!> "blabla"` and don't need to worry what the target type is.
Example usage here:
https://gist.github.com/asik/ce229023fb0eb153bde6aacc384d8ac4

Agreed it would be better to avoid needing this, but just to say there's a half-decent workaround.

**Comment by tig** [comment]
Changed title of this Issue from "F# the ustring API makes it annoying to use F#". 

In v2.0 we should remove the dependency on ustring (at least externally) and use System.Rune instead. While ustring is neat, the fact that artifacts of it are exposed via the public Terminal.Gui API is problematic (F# support just being one). Another example is just simple usage of the API requires users to import NStack (see the C# Example in the main README).
